apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-http-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http
  template:
    metadata:
      labels:
        app: java-http
    spec:
      containers:
        - name: java-http
          image: mtolv/java-http-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-http-service
spec:
  selector:
    app: java-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
